# Generated by Django 5.2.10 on 2026-01-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(help_text='e.g., P001', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('vocalist', 'Vocalist'), ('instrumentalist', 'Instrumentalist'), ('both', 'Both')], max_length=20)),
                ('primary_instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_vocal', models.BooleanField(default=False)),
                ('harmony_vocal', models.BooleanField(default=False)),
                ('preferred_keys', models.CharField(blank=True, help_text='e.g., E, F, G, Bb', max_length=100)),
                ('style_strengths', models.TextField(blank=True, help_text='Musical style strengths')),
                ('frequency', models.CharField(blank=True, choices=[('core', 'Core'), ('regular', 'Regular'), ('occasional', 'Occasional')], max_length=20)),
                ('availability', models.TextField(blank=True, help_text='Availability notes')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(help_text='e.g., SV001', max_length=10, unique=True)),
                ('service_date', models.DateField()),
                ('service_name', models.CharField(help_text='e.g., Sunday Morning Worship', max_length=200)),
                ('band_notes', models.TextField(blank=True, help_text='Notes for the band')),
                ('service_notes', models.TextField(blank=True, help_text='General service notes')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(help_text='e.g., S001', max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('default_key', models.CharField(help_text='e.g., D, G, A', max_length=10)),
                ('tempo', models.CharField(blank=True, choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], max_length=20)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('arrangement_notes', models.TextField(blank=True)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('comfort_level', models.CharField(blank=True, help_text="Band's comfort level", max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_order', models.IntegerField(help_text='Order in the service (1, 2, 3...)')),
                ('key_used', models.CharField(help_text='Key used in this service', max_length=10)),
                ('length', models.IntegerField(blank=True, help_text='Length in minutes', null=True)),
                ('lead_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='band.person')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='band.service')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.song')),
            ],
            options={
                'ordering': ['service', 'song_order'],
                'unique_together': {('service', 'song_order')},
            },
        ),
        migrations.CreateModel(
            name='PersonSongPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(help_text='e.g., E001', max_length=10, unique=True)),
                ('preferred_key', models.CharField(blank=True, help_text='Preferred key for this person', max_length=10)),
                ('can_lead', models.BooleanField(default=False, verbose_name='Can Lead')),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_preferences', to='band.person')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_preferences', to='band.song')),
            ],
            options={
                'verbose_name': 'Person-Song Preference',
                'ordering': ['person__name', 'song__title'],
                'unique_together': {('person', 'song')},
            },
        ),
    ]
