# Generated by Django 5.2.10 on 2026-02-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(blank=True, help_text='Beats per minute', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='tempo',
            field=models.CharField(blank=True, choices=[('slow', 'Slow'), ('med_slow', 'Med Slow'), ('medium', 'Medium'), ('med_fast', 'Med Fast'), ('fast', 'Fast')], max_length=20),
        ),
    ]
