# Generated by Django 5.2.10 on 2026-02-08 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_song_bpm_alter_song_tempo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Churches',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(help_text='e.g., P001', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='plan_id',
            field=models.CharField(help_text='e.g., SV001', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(help_text='e.g., S001', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='band.church'),
        ),
        migrations.AddField(
            model_name='service',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='band.church'),
        ),
        migrations.AddField(
            model_name='song',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='band.church'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('church', 'person_id')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('church', 'plan_id')},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('church', 'song_id')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin (Worship Leader)'), ('user', 'User (Band Member)')], default='user', max_length=20)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='band.church')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
