# Generated by Django 5.2.10 on 2026-02-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_make_church_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
