# Generated by Django 5.2.10 on 2026-02-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.CharField(blank=True, help_text='Song length e.g. 4:48', max_length=10),
        ),
    ]
